name: Sync to Deploy Remote

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Sync to deploy repository
        run: |
          git remote add deploy https://${{ secrets.DEPLOY_REPO_PAT }}@github.com/abdelrahman-swe/blink.git
          git push deploy main --force-with-lease